### ISSUE TITLE
ovpn file

### ISSUE THREAD

**Issue by mayurteraiya** [ashraf789/Cake-VPN#10]
Hello,

can you share details for ovpn file. ? how we can get it ?

**Comment by ashraf789** [comment]
You can download free Ovpn file from this website https://www.vpngate.net/en/
But it's for a limited time. Also, you can set up your own VPN server read details from here 
https://www.digitalocean.com/community/tutorials/how-to-set-up-an-openvpn-server-on-ubuntu-18-04

**Comment by tinycellstuan** [comment]
i recc linode as a VPN server https://www.linode.com/lp/youtube-viewers/?ifso=wolfgang its cheaper and much more safer when it comes to VPS privacy
