### ISSUE TITLE
Expired OpenVPN Library

### ISSUE THREAD

**Issue by HiddenPirates** [ashraf789/Cake-VPN#103]
By using this open vpn library, when I am building android app bundle, it's not working.

**Comment by Ultimatetinycellstuan** [comment]
did you not read the Readme.md file? This project is not updated as usual and very inactive

**Comment by ashraf789** [comment]
> 

Hello,
Did you try with gradle.properties
android.bundle.enableUncompressedNativeLibs=false

https://github.com/ashraf789/Cake-VPN/blob/master/gradle.properties

**Comment by Deepanshusuman** [comment]
FATAL EXCEPTION: main
    Process: com.someapp.vpn, PID: 14198
    android.app.RemoteServiceException: Bad notification(tag=null, id=-183992402) posted from package com.someapp.vpn, crashing app(uid=12076, pid=14198): Couldn't create icon StatusBarIcon(icon=Icon(typ=RESOURCE pkg=com.someapp.vpn id=0x7f070071) visible user=0 )

**Comment by Deepanshusuman** [comment]
it is working fine
