### ISSUE TITLE
Server IP Issue!

### ISSUE THREAD

**Issue by brittle123** [ashraf789/Cake-VPN#106]
Hello @ashraf789 ! Hope you're doing well,.. the problem is that i downloaded the config files from your mentioned site https://www.vpngate.net/en/ ,.. sometime it's connected to the server and sometimes it gives me Auth failure error. Please can you provide me the config files that you're using in your playstore app in which all servers are connecting without any error.
Please do let me know ASAP!
Thanks & Regards

**Comment by ashraf789** [comment]
> Hello @ashraf789 ! Hope you're doing well,.. the problem is that i downloaded the config files from your mentioned site https://www.vpngate.net/en/ ,.. sometime it's connected to the server and sometimes it gives me Auth failure error. Please can you provide me the config files that you're using in your playstore app in which all servers are connecting without any error. Please do let me know ASAP! Thanks & Regards

https://www.vpngate.net/en/  is for testing purposes only and their VPN get expired very soon. if you build your own app then it's better to set up your own VPN server.

**Comment by ashraf789** [comment]
> And in your this demo , USA and SWEDEN is not working. Can you fix this ASAP!

It's an example VPN profile and from VPNgate so no matter how many times I update a new profile it will expire soon.

**Comment by brittle123** [comment]
So Sorry for the late response! Can you tell me how am I going to set my own server? and where I'm going to set my own server,.. is it on android or windows?

**Comment by ashraf789** [comment]
To setup open VPN server 
You may follow these tutorials
https://www.cyberciti.biz/faq/howto-setup-openvpn-server-on-ubuntu-linux-14-04-or-16-04-lts/
https://openvpn.net/community-resources/how-to/
