### ISSUE TITLE
upgrade to android 31

### ISSUE THREAD

**Issue by Deepanshusuman** [ashraf789/Cake-VPN#107]
upgrade to android sdk 31 as android sdk 32 alpha is out 
or how to upgrade it

**Comment by ashraf789** [comment]
I will check the new version.

**Comment by Deepanshusuman** [comment]
how did you compile .so files or how to use ovpn3 <-

**Comment by ashraf789** [comment]
> how did you compile .so files or how to use ovpn3 <-

That's lots of work to update the library. I changed my programming track from android to asp.net so it will be late to update anything on this project except if there any bug on the current source code.
 
You can follow the guideline from here to update library.
https://github.com/ashraf789/Cake-VPN/issues/34

**Comment by Deepanshusuman** [comment]
thanks
