### ISSUE TITLE
Now apk upload Not Allow play store VPN Not Connecting after app Published in play store 

### ISSUE THREAD

**Issue by yeasin989** [ashraf789/Cake-VPN#108]

**Comment by Ultimatetinycellstuan** [comment]
Just get a new apk file and a new vpn. This project is quite outdated

**Comment by Ultimatetinycellstuan** [comment]
Make sure to redo the ui

**Comment by ashraf789** [comment]
Try with gradle.properties
android.bundle.enableUncompressedNativeLibs=false

https://github.com/ashraf789/Cake-VPN/blob/master/gradle.properties
