### ISSUE TITLE
How get server lists Ovpn from server

### ISSUE THREAD

**Issue by javaddeveloper** [ashraf789/Cake-VPN#109]
Hello friend

This framework is realy great and i like it.
I have a question about .Ovpn files

how can i get list of ovpn file from server and save it in SharedPreference or Sqlite database ?

Could you give me sample of code for this

**Comment by ashraf789** [comment]
> how can i get list of ovpn file from server and save it in SharedPreference or Sqlite database ?


You need to write an API that will send you .ovpn files from server then save those files to local. 

> Could you give me sample of code for this

I don't have any open-source for this.
