### ISSUE TITLE
Clicking on notification doesn't open app

### ISSUE THREAD

**Issue by javaddeveloper** [ashraf789/Cake-VPN#111]
Hello
When i click on notification to open up main application , it doesn't work
I want to open app when click on notification
Could you review it

**Comment by ashraf789** [comment]
It's working fine. please let me know more about your device.  
https://play.google.com/store/apps/details?id=com.ashraf789.cakevpn

**Comment by javaddeveloper** [comment]
I have changed my main activity name and that problem happened and i solve it by rename MainActivity

Now i have another question

I want user cant dissconnect vpn from notification 
when user click on disconnect on notification open main application and user disconnect VPN from MainActivity

**Comment by ashraf789** [comment]
01. to change manactivity update here: 
https://github.com/ashraf789/Cake-VPN/blob/master/vpnLib/src/main/java/de/blinkt/openvpn/core/OpenVPNService.java#L482

02. update disconnect activity to your main activity:
https://github.com/ashraf789/Cake-VPN/blob/master/vpnLib/src/main/java/de/blinkt/openvpn/core/OpenVPNService.java#L445

**Comment by javaddeveloper** [comment]
Thank you for response 
How can change this line to open main app when user click on disconnect ?

https://github.com/ashraf789/Cake-VPN/blob/master/vpnLib/src/main/java/de/blinkt/openvpn/core/OpenVPNService.java#L445

**Comment by ashraf789** [comment]
Replace DisconnectVPNActivity.class with your mainactivity so when click disconnect button, app will open your mainactivity

**Comment by javaddeveloper** [comment]
Hello 
could you say which number of line is for notification update states?

in the notification show text line to update states i want that text input to change it

**Comment by ashraf789** [comment]
I can't remember. Please debug notification-related code.
Thanks
