### ISSUE TITLE
Difference

### ISSUE THREAD

**Issue by mahdikarimi5509** [ashraf789/Cake-VPN#113]
Your source code is different from the app you uploaded to the Play Store.
Please upload the source code
Or update

**Comment by ashraf789** [comment]
which part is different?

**Comment by mahdikarimi5509** [comment]
> which part is different?

Hello
The IP part is inside the application you uploaded to Google Play, but does not exist in the source code
Next, a fixed notification is attached in the app within Google Play, but not in the source
Can you help?

**Comment by ashraf789** [comment]
1. For notification please find the solution from here
https://github.com/ashraf789/Cake-VPN/issues/111

2. those IP are static, it's just another text field that I don't want to add to this project.

**Comment by ashraf789** [comment]
![image](https://user-images.githubusercontent.com/13873490/150640588-c63bf3f4-bbe9-4ea3-9439-d8f83970b87c.png)
Static like this server information.

**Comment by mahdikarimi5509** [comment]
> 1. For notification please find the solution from here
>    [Clicking on notification doesn't open app #111](https://github.com/ashraf789/Cake-VPN/issues/111)
> 2. those IP are static, it's just another text field that I don't want to add to this project.

![Uploading Screenshot_20220122-173254_Cake VPN.jpg…]()

I mean, this is a notification. The program has Google Play, but it does not have a source code. Can you help?

**Comment by mahdikarimi5509** [comment]
https://s4.uupload.ir/files/screenshot_20220122-173254_cake_vpn_nlf.jpg

I mean, this is a notification. The program has Google Play, but it does not have a source code. Can you help?

**Comment by ashraf789** [comment]
Build this project and run it to in your device.

**Comment by mahdikarimi5509** [comment]
https://s4.uupload.ir/files/screenshot_20220122-190040_cake_vpn_wu82.jpg
https://s4.uupload.ir/files/screenshot_20220122-190034_cake_vpn_9uhl.jpg

The notification does not go up on my device

**Comment by ashraf789** [comment]
Please install this app and check if there notifications on your device.
https://play.google.com/store/apps/details?id=com.ashraf789.cakevpn

**Comment by ashraf789** [comment]
If I am not wrong you modified the source code. 
if so then the problem is similar to this issue
https://github.com/ashraf789/Cake-VPN/issues/111

**Comment by mahdikarimi5509** [comment]
You can send me the original program file to check

**Comment by ashraf789** [comment]
This is the original source code. please download fresh source code then build APK.
If the result is same then share your source code i will check for you.

**Comment by mahdikarimi5509** [comment]
I can not decompress the source code, you can help me

**Comment by mahdikarimi5509** [comment]
Send it to me if you can

**Comment by mahdikarimi5509** [comment]
[Cake-VPN-master.zip](https://github.com/ashraf789/Cake-VPN/files/7919129/Cake-VPN-master.zip)
I have downloaded this file

**Comment by mahdikarimi5509** [comment]
https://github.com/ashraf789/Cake-VPN/releases/tag/V2.0



Can I download it from here?
