### ISSUE TITLE
Private Key Password

### ISSUE THREAD

**Issue by ALISCHILLER** [ashraf789/Cake-VPN#115]
Hello, thank you for your effort. The question I had was about the private key password. Is there a place in the code to add it?

**Comment by ALISCHILLER** [comment]
Hello, thank you for your effort. The question I had was about the private key password. Is there a place in the code to add it?

**Comment by ashraf789** [comment]
https://github.com/ashraf789/Cake-VPN/blob/master/app/src/main/java/com/lazycoder/cakevpn/view/MainActivity.java

![image](https://user-images.githubusercontent.com/13873490/153786710-3b5c4937-c570-4cf9-9904-febdb207fe94.png)
