### ISSUE TITLE
OpenVpn Config file

### ISSUE THREAD

**Issue by Tanv33rA** [ashraf789/Cake-VPN#116]
I am planning to have my own openVpn server for multiple clients . But I don't know how to create ovpn file that can be used for each client. I have idea of duplicate-cn but I am looking for robust solution. Thanks

**Comment by ashraf789** [comment]
Your issue is not clear, what do you expect from this app?

**Comment by Tanv33rA** [comment]
Thanks for your response . This app is working perfect. I just want to use my own openVpn server installed on EC2 VPS . I have no idea how to create config file of openVPN instead of using vpngate's files . I am looking for help to create ovpn file . Thanks

**Comment by ashraf789** [comment]
You can try this tutorial
https://www.cyberciti.biz/faq/howto-setup-openvpn-server-on-ubuntu-linux-14-04-or-16-04-lts/
https://openvpn.net/community-resources/how-to/
