### ISSUE TITLE
Any plan to use json file as server list?

### ISSUE THREAD

**Issue by ombapit** [ashraf789/Cake-VPN#121]
Did you have a plan to load list server and connection from json file?

**Comment by ashraf789** [comment]
To load JSON data from a server you need API. if you have a ready api then it's not hard to update the current flow with api data. 
I already implemented it with a live app which is live on the google play store 
But the API source code that i made it's not open source.

**Comment by ashraf789** [comment]
> Did you have a plan to load list server and connection from json file?

Don't have a plan to update the current source code with API data.
