### ISSUE TITLE
I add assets ovpn file , it is connected but ip not changed

### ISSUE THREAD

**Issue by ppking2897** [ashraf789/Cake-VPN#122]
I use the ovpn file from https://www.vpngate.net/en/ , and i use mac openVpn app set this ovpn file ,

it is worked and ip was changed

but i use this file to add app , it seem likes to connected , but when i check up from https://www.whatismyip.com/ 

ip is not changed 

Is ovpn file error or something i missing to set up , because your default ovpn file can lets the ip changed and it is worked

If you have solution or any idea can tip me how to solve this problem ,  I would appreciate it 

Thank you!!

**Comment by ashraf789** [comment]
There are no other settings. Just replace OVPN is done. 
You can check with the incognito window. sometimes browsers display cached data.

**Comment by ppking2897** [comment]
> There are no other settings. Just replace OVPN is done. You can check with the incognito window. sometimes browsers display cached data.

Thank you , I will try it again 

I have one more question , in my project i build openVpn server by nas , so i use nas environment create ovpn file 

but i put this file to your app or OpenVpn App ,  they are have same situation , that is status bar have vpn connected icon

the ip still not changed , have you any idea to this situation?

**Comment by ashraf789** [comment]
When you connect with VPN, your IP will be changed with your OpenVPN server IP. 
" ip still not changed , have you any idea to this situation"
-> I don't have any idea.

**Comment by ppking2897** [comment]
> When you connect with VPN, your IP will be changed with your OpenVPN server IP. " ip still not changed , have you any idea to this situation" -> I don't have any idea.

Thanks for your reply, I will look for other reasons, thanks again
