### ISSUE TITLE
Android 12 stuck at connecting

### ISSUE THREAD

**Issue by TrystanTanck** [ashraf789/Cake-VPN#123]
i used your ics-openvpn in my app, it is working fine, but when installed at android 12 device, once connect the app will crash, then i fix the AndroidManifest.xml, it turns out stuck at connecting

**Comment by ashraf789** [comment]
Can you try the live app with your android 12 device?
https://play.google.com/store/apps/details?id=com.ashraf789.cakevpn

**Comment by TrystanTanck** [comment]
Hi, sorry for late reply, i tried the live app it is still same stuck at connecting

**Comment by TrystanTanck** [comment]
Hi sorry for the late reply, I tried the live app on android 12 device it is worked. And I had figured out what's the problem, i change my project compilesdkversion and targetsdkversion back to 30 and now it is worked. anyways thanks for your prompt response.
