### ISSUE TITLE
Defective OpenSSL Version (OpenSSL 1.1.1g)

### ISSUE THREAD

**Issue by brobin002** [ashraf789/Cake-VPN#126]
First of all many thanks to ashraf789 for your amazing work :)

I have this error on the Google Play Console. Does anyone know how to update the OpenSSL Version?

**Comment by ashraf789** [comment]
Hi @brobin002,
This is the first time heard this error. Can you write more details with a screenshot? 

Thanks

**Comment by ashraf789** [comment]
Not sure where is the problem. The cakevpn app is live https://play.google.com/store/apps/details?id=com.ashraf789.cakevpn

If you use any other library then check those.

**Comment by brobin002** [comment]
I am not using other lib which depend on openSSL and never had this error before. I think you'll have this error on your future cakevpn update but you'll still be able to release the update.

I think vpnLib use pre build lib of openSSL v1.1.1g which causes the error (OpenVPN uses the OpenSSL library to provide encryption).

**Comment by brobin002** [comment]
Yeah I might be using another lib which depends on openSSL. I'll investigate.

But openvpn use openSSL. Do you know which openSSL version is used in cakevpn?

**Comment by ashraf789** [comment]
Ah, this i don't know which OpenSSL they used in the library.

**Comment by melniqw** [comment]
Met the same problem. Google says it is related to NDK, so in my project openvpn is the only NDK using library.

**Comment by kraken0706** [comment]
Hi,
I have the same problem, has the problem been solved?

**Comment by moovendran-368** [comment]
> Ah, this i don't know which OpenSSL they used in the library.

Please check your play Console goto production current version

**Comment by brobin002** [comment]
They are using OpenSSL 1.1.1g version

**Comment by gnanesh023** [comment]
#131 Updated to OpenSSL 1.1.1l , now There is no issue with  Publishing
