### ISSUE TITLE
Question: Is the openvpn library up to date?

### ISSUE THREAD

**Issue by mj700** [ashraf789/Cake-VPN#13]
Hi, 
Thank you for publishing the code, is the openvpn library up to date?

I have been using some other opensource apps but they have had issues due to old openvpn library.

**Comment by ashraf789** [comment]
It is also the same.
But when I get the issues I try to solve it. Also, the open-source lover tries to solve the issue.

**Comment by mj700** [comment]
Yeah I'd love to solve the issus as long as as I can.

In regard to your VPN application, it sometimes stops connectivity, I'm trying to find out if there is something wrong with the client or not.

**Comment by ashraf789** [comment]
That's nice, if you find out the issue then please create a new issue with details. 

Thanks
