### ISSUE TITLE
After library update, cant connect using config from vpngate.net

### ISSUE THREAD

**Issue by gemeauxph** [ashraf789/Cake-VPN#134]
I noticed an issue connecting using ovpn files from vpngate but when using other ovpn files it's working fine. I think the issue is from the .so files in jniLibs because when I try the old version, it would work again. Im not really sure why only files from vpngate is not working.

**Comment by Vladoo7** [comment]
did you solve the problem?

**Comment by Vladoo7** [comment]
> I noticed an issue connecting using ovpn files from vpngate but when using other ovpn files it's working fine. I think the issue is from the .so files in jniLibs because when I try the old version, it would work again. Im not really sure why only files from vpngate is not working.


did you solve the problem?
