### ISSUE TITLE
AlwaysOnVpn 

### ISSUE THREAD

**Issue by khashayar-k** [ashraf789/Cake-VPN#15]
Hi @ashraf789 how are you doing ,I was wondering if you could add the AlwaysOnVpn feature to the  app so if the user restarts the phone the vpn connects automatically on boot, so i looked into Ics-openvpn source and i found a class named OnBootReciver so if you could add this it would be amazing

**Comment by ashraf789** [comment]
Thanks for your recommendation, i will try to update on next version.

**Comment by ashraf789** [comment]
Also, if you want you can update the library.

**Comment by ashraf789** [comment]
Hello, 
Today I was going to implement this feature but I think it's not a good feature for the VPN app. 
As the user does not use a VPN at all times. Very few users use a VPN app at all times. 
 
I am sorry I am not going to implement this feature on app.
