### ISSUE TITLE
UDP protocol?

### ISSUE THREAD

**Issue by Aidzo** [ashraf789/Cake-VPN#2]
Really awesome APK nice and simple just one issue I seem to have.
Apps doesn't seem to connect when using UDP protocol and when tls-crypt is within .ovpn config

**Comment by ashraf789** [comment]
Thanks for your review.
I used open vpn official library it support both UDT and TCP protocol also ipv6 support.

I will check your issue.

**Comment by Aidzo** [comment]
Thanks very much for looking into it must be something to do with my .ovpn as includes `<tls-crypt>
-----BEGIN OpenVPN Static key V1-----
Key.........
-----END OpenVPN Static key V1-----
</tls-crypt>`

**Comment by ashraf789** [comment]
Someone face this same issue and after research he solve the problem like this way.

openvpn connect does not support tls-crypt and for anyone with this issue just remove any line with tls in your /etc/openvpn/server.conf
and then remove the tls-crypt key in your client.ovpn file it will work
