### ISSUE TITLE
How To get Server Public IP like 213.133.142.71

### ISSUE THREAD

**Issue by techticjaypatel** [ashraf789/Cake-VPN#20]

**Comment by ashraf789** [comment]
Sorry, I don't know about this.

But you can try these 
https://crunchify.com/how-to-get-server-ip-address-and-hostname-in-java/
https://stackoverflow.com/questions/6064510/how-to-get-ip-address-of-the-device-from-code
https://stackoverflow.com/questions/43887189/android-get-the-ip-address-of-a-server-name-in-local-area-network

Thank you.
