### ISSUE TITLE
Clicking on Connect button while a connection is in progress

### ISSUE THREAD

**Issue by max4444** [ashraf789/Cake-VPN#21]
Hi, 

Clicking on Connect button doesn't cancel/disconnect the connect process while a connection is in progress... What if a user needs to cancel an in-progress connection?

Anyway thank you for nice app!

**Comment by ashraf789** [comment]
Thank you, i will fix it soon.

**Comment by max4444** [comment]
i was busy with personal life and just got some time to check it out, good job it's all fine now!
