### ISSUE TITLE
can't connect on android API 29 / Android 10

### ISSUE THREAD

**Issue by riskiadi** [ashraf789/Cake-VPN#22]
can't connect on android API 29 / Android 10 , no errors log found. I think maybe about android permission sdk 23
https://developer.android.com/guide/topics/manifest/uses-permission-sdk-23-element

Heres my gradle

android {
    compileSdkVersion 29
    buildToolsVersion "29.0.2"
    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

**Comment by riskiadi** [comment]
![ss](https://user-images.githubusercontent.com/18738645/77237655-870e1880-6bfc-11ea-95f1-7c1b04d902e8.gif)

**Comment by ashraf789** [comment]
I think it is a problem with the free ovpn server. I just test on my emulator Pixel 3a API 29 and it's working fine.
 
But for you, I update a new server.
Follow the step to test again.
1. Delete your old app.
2. Pull latest source code
3. Build apk and run app on device.
4. Select US server and click connect.

Late me know if you face the same issue.
Thanks.

**Comment by riskiadi** [comment]
> I think it is a problem with the free ovpn server. I just test on my emulator Pixel 3a API 29 and it's working fine.
> 
> Follow the step to test again.
> 
> 1. Delete your old app.
> 2. Change the OVPN file with your own server OVPN file.
> 3. Build apk and run app on device.
> 4. Select your newly added server and press connect button.
> 
> Late me know if you face the same issue.
> Note: currently all free ovpn not working.
> Thanks.

Yes fixed on my Android 10 device now, thanks

**Comment by riskiadi** [comment]
my current gradle is
targetSdkVersion 29 (make me cant connect)

now i change targetSdkVersion 28 this can fixed this problem
