### ISSUE TITLE
Can't connect to the servers after your last update ? 

### ISSUE THREAD

**Issue by salaheddinegit** [ashraf789/Cake-VPN#23]
Hi

when you choose the server and click on connect it run in loop, reconnecting and authenticating without getting a real connection to the server

**Comment by ashraf789** [comment]
All free ovpn server is currently not working please use your own server then if you face same problem let me know. 

The issue is related to issue #22

**Comment by salaheddinegit** [comment]
so no solution to use free vpn servers even with ovpn ? 

Thank you sir

**Comment by ashraf789** [comment]
Yeah, currently free ovpn is not working.
