### ISSUE TITLE
account 

### ISSUE THREAD

**Issue by gg-mayee** [ashraf789/Cake-VPN#24]
I would like to ask sir if there's a way I could add an accounts tab in which I could put their the ovpn user and pass instead of being embed in the java? how could I implement it sir?

**Comment by ashraf789** [comment]
Yes, you can do that.
You need to read a .ovpn extension file from local storage then use the ovpn file instead of the asset folder ovpn file.

**Comment by ashraf789** [comment]
You can check this 
https://stackoverflow.com/questions/14768191/how-do-i-read-the-file-content-from-the-internal-storage-android-app

instead of .txt use .ovpn

**Comment by gg-mayee** [comment]
![image](https://user-images.githubusercontent.com/62453367/77369180-f15bc000-6d98-11ea-8a0b-735b53c29f30.png)
this is what i meant sir, ps. photo not mine just an example of what i wanted to figure out. 
I want that instead of harcoded username and password. It will be through a dialouge where you can save the credentials.

**Comment by ashraf789** [comment]
Instead of saving user name and password on java code you can save the data on sqlite or sharedpreference. 

As per your requirement, please develop your own logic.
