### ISSUE TITLE
Cannot connect to any vpn server.

### ISSUE THREAD

**Issue by zohaib1sahni** [ashraf789/Cake-VPN#25]
Hello
As you mentioned that you are using free server from https://www.vpngate.net/en/.
But no server is connecting at the moment.

**Comment by ashraf789** [comment]
Yes, currently all free server is not working.

**Comment by ashraf789** [comment]
You can try this link
https://www.freeopenvpn.org/en/

**Comment by zohaib1sahni** [comment]
Thanks and ive downloaded some servers from vpn gate.
your code is perfect and new servers are working with.
what if i want to use any paid server for my user to have some premium feature in my app?
Does   https://www.vpngate.net/en/ offers some paid server and will this code be compatible with paid server configuration?
All the configuration is currently in the .ovpn file.

**Comment by ashraf789** [comment]
Don't worry the configuration is the same just replace the .ovpn file with your paid .ovpn file.
If you want to give premium feature in that case set up your worn server.  buy a cloud server then install VPN. If you do not interest in your own setup. You can still buy a server from digitalocean.com 
Lots of other site.

**Comment by zohaib1sahni** [comment]
Thanks.
https://surfshark.com/servers
They are offering unlimited devices. I think this would be better for own app and premium feature.

**Comment by zohaib1sahni** [comment]
Iv checked many apps on github that are using OpenVpn protocol.
They all are using their module de.blinkt.openvpn (Open Vpn Github project). And you are also using same module.
Is it safe to use their module for vpn connectivity?
Google will not put any association on it?

**Comment by ashraf789** [comment]
Is it safe to use their module for vpn connectivity?
-> you mean you want to use their .ovpn file? if yes then it is not safe.

Google will not put any association on it?
-> i am not sure about this.

**Comment by zohaib1sahni** [comment]
Im asking about their VPN module means their code for connectivity like their classes of VpnService and VpnProfile e.t.c. 
![sample](https://user-images.githubusercontent.com/63712021/79568649-0f9c9f00-806b-11ea-9eb5-03196281ca19.PNG)

**Comment by zohaib1sahni** [comment]
obviously ill use .ovpn files for free servers.

**Comment by ashraf789** [comment]
No problem at all,
But according to my requirement, I have updated lots of code from their module. so if you want to directly replace their code you will get some error and you have to fix those errors by yourself.

**Comment by zohaib1sahni** [comment]
Sure Ive to replace some code. I was confused whether i should use their some classes because all vpn apps are using OpenVpn protocol and they are using their classes and code.
Thanks!!!!1
