### ISSUE TITLE
It does not work on some devices!

### ISSUE THREAD

**Issue by soheilazimi2017** [ashraf789/Cake-VPN#26]
Hi Syed

Your App is very good, but it doesn't work at all on some devices!
Please solve the problem
Thanks

**Comment by ashraf789** [comment]
Hello,
Could you please write down the details of the problem. 
Also, your device details in which you face the problem. 

Thanks

**Comment by soheilazimi2017** [comment]
Samsung s50s

According to the Log's I receive, all methods are executed, but the connection is not established.

**Comment by max4444** [comment]
Did you mean that the same OpenVPN config works on other devices? There might be an issue with your VPN config, are using the files included in the App or you have your own config files? Can you please attach some log files?

**Comment by soheilazimi2017** [comment]
I don't know exactly what the problem is!
In addition to the configuration files in the main project (your git project), I have added 4 more files, some of which are linked below, which you can check.
It doesn't even connect to these files!

http://s10.picofile.com/d/8394676468/f1f5e137-06a4-49f7-a90d-17e0ec5a9fd1/canada.ovpn
http://s10.picofile.com/d/8394676534/bab2072d-d681-49bd-9eb9-2b47f90581c9/japan1.ovpn
http://s10.picofile.com/d/8394676600/277081a0-6e26-4c07-93f5-b0834562fc71/taiwan.ovpn

In some phones it is connected with a password 'vpn' but in others it is not connected at all.

**Comment by max4444** [comment]
Can you please test the attached config file?

[US2.zip](https://github.com/ashraf789/Cake-VPN/files/4507871/US2.zip)

**Comment by max4444** [comment]
Can you please test the attached config file?

[US2.zip](https://github.com/ashraf789/Cake-VPN/files/4507887/US2.zip)

**Comment by soheilazimi2017** [comment]
Yes, Sure

**Comment by soheilazimi2017** [comment]
Unfortunately, it still works on my phone.
But it doesn't work on other people's phones!

**Comment by max4444** [comment]
What is the exact device brand, build, version and also Android version?

Does it show any logs?

**Comment by soheilazimi2017** [comment]
http://s10.picofile.com/file/8394691584/shot1.jpeg
http://s11.picofile.com/file/8394691800/shot2.jpeg

**Comment by soheilazimi2017** [comment]
Were you able to find the problem?

**Comment by max4444** [comment]
Hi Soheil, sorry i don't have physical access to any of the devices you mentioned but i'll try to test if i get the chance

**Comment by soheilazimi2017** [comment]
OK, thanks a lot!

**Comment by soheilazimi2017** [comment]
I'm still waiting for you. Please solve the problem
Thanks

**Comment by ashraf789** [comment]
Hi,
@soheilazimi2017 I have tested the app couple of devices but I could not found the problem. I do not have any devices that you are facing the problem so it's difficult to solve your problem.

**Comment by soheilazimi2017** [comment]
Hello and don't be tired of your service

I also tested this version, it didn't matter, and I don't think it's a problem with your program, and it happens on different networks.
