### ISSUE TITLE
dns-leak issue

### ISSUE THREAD

**Issue by khashayar-k** [ashraf789/Cake-VPN#27]
hi @ashraf789 
i just found a bug and its really odd in xiaomi devices the phone refuses to use vpn profile dns is there any way that you could fix it i tried everyting its not from the server im sure and i tried the same vpn profile in openvpn app from google play and it works there

**Comment by ashraf789** [comment]
Hi,
Could you please send me the log message.

Thanks

**Comment by khashayar-k** [comment]
i fixed it
 the line
`public boolean mOverrideDNS = false;`
in the VpnProfile must be set true

**Comment by ashraf789** [comment]
Waw, nice.

**Comment by max4444** [comment]
> 
> 
> i fixed it
> the line
> `public boolean mOverrideDNS = false;`
> in the VpnProfile class must be set true

@khashayar-k 

Even though you've marked the issue as closed but DNS leak is something that shouldn't be ignored.. i just want to make sure if this has something with the client as i don't see it here.., how can i reproduce it?
