### ISSUE TITLE
Add ability

### ISSUE THREAD

**Issue by Dazmed707** [ashraf789/Cake-VPN#31]
Add an option so that the settings of an .ovpn file can be encrypted
and that encrypted file is normally opened on another device but the settings cannot be seen.
Only the file can be decrypted in the same file that was encrypted.

**Comment by ashraf789** [comment]
In that case, the app also can not open the encrypted file and will not be able to establish a connection with VPN server. Did you think about this problem?

Thanks.

**Comment by Dazmed707** [comment]
The application would have to internally decrypt the file .. and save it to some path temporarily or something like that

**Comment by ashraf789** [comment]
Sorry, this feature is not suitable for this app.

**Comment by Deepanshusuman** [comment]
Use api instead and encrypt and decrypt data while storing in shared preferences
