### ISSUE TITLE
how to config server?

### ISSUE THREAD

**Issue by hosseiniSeyRo** [ashraf789/Cake-VPN#33]
please explain me how to config server? what do i do?

**Comment by ashraf789** [comment]
Well, to configure a server you required a cloud server like AWS, digital ocean, etc. 

There are already lots of tutorial related to configuring the OpenVPN server. Please follow those tutorials. like bellow

https://www.digitalocean.com/community/tutorials/how-to-set-up-an-openvpn-server-on-ubuntu-18-04
https://blog.ssdnodes.com/blog/tutorial-installing-openvpn-on-ubuntu-16-04/

Thanks.
