### ISSUE TITLE
OpenVpnThread Null Exception with SDK 29

### ISSUE THREAD

**Issue by MubashirMurtaza** [ashraf789/Cake-VPN#35]
when you set the target sdk to 29, openvpn gives null exception on OpenVpnthread i tried to solve this but failed,, i think may this this is becasue of file system andorid changed in sdk 29,, but on the other hand i found that the  .so files are n more works with sdk29 may be this is the reason we are getting null exception.

**Comment by Deepanshusuman** [comment]
i am also waiting
