### ISSUE TITLE
Vpn connects in debug apk but Vpn is not connecting in Live Bundle on play store.

### ISSUE THREAD

**Issue by zohaib1sahni** [ashraf789/Cake-VPN#36]
Vpn connects in debug apk but Vpn is not connecting in Live Bundle on play store.
My App is live on play store. but vpn is not connecting.
what will be the issue?

**Comment by ashraf789** [comment]
Sorry, it's not related to the app.

**Comment by Deepanshusuman** [comment]
Same issue did you solve the problem
