### ISSUE TITLE
Awesome work, but not working on Android 10 

### ISSUE THREAD

**Issue by ItsYourAhmed1** [ashraf789/Cake-VPN#4]
![android10](https://user-images.githubusercontent.com/41875913/72963068-10a99180-3dd8-11ea-9a29-6c655f28df48.PNG)

**Comment by ashraf789** [comment]
Thank you. 
I will fix the issue.

**Comment by ItsYourAhmed1** [comment]
Yeah waiting.

**Comment by akyzi007** [comment]
Hello,
Getting same issue. Can you please fix this issue?
Thanks in Advance

**Comment by ashraf789** [comment]
Sorry i am on vacation. I will fix the issue after back to work. Please wait couple of days. 

Thanks

**Comment by akyzi007** [comment]
Sure, Take your time.
Waiting for solution.

**Comment by ItsYourAhmed1** [comment]
Hello, Ashraf!
How are you?
What i found about the android 10 not working error is that i think the latest ics-openvpn library code is not used in the app because if we use OpenVPN app , the root app. This error  is not there in that app. Can you guide me how to import the latest ics-openvpn library ...

**Comment by ItsYourAhmed1** [comment]
From where i can find latest vpn-release.aar file ?

**Comment by ashraf789** [comment]
Sorry i was on vacation, i will try to fix the issue within sunday. 

I have generated the aar file by my own.

**Comment by ItsYourAhmed1** [comment]
Thankyou. Waiting brother.

**Comment by ashraf789** [comment]
I made the library as public now your can modify the library.
Currently i am working on this issue, if you want to contribute you are welcome.

**Comment by ItsYourAhmed1** [comment]
Yes. I would happily contribute and i am also trying to fix this issue.

**Comment by ItsYourAhmed1** [comment]
Working on, i have imported the project and at this time, vpn is not connecting on any device and app is crashing.

**Comment by ashraf789** [comment]
Could you please check again.

**Comment by ItsYourAhmed1** [comment]
Okay give me some time. I will clone and inform you.

**Comment by ItsYourAhmed1** [comment]
For the time now, i have checked on device with Android pie, it working now.

**Comment by ItsYourAhmed1** [comment]
Yeah confirmed working on all devices below and equal to android 9 version.

**Comment by akyzi007** [comment]
what about android 10?  still getting the same issue 
"VPN Got java.lang.NullPointerException: Attempt to invoke virtual method 'void java.lang.Process.destroy()' on a null object reference".
@ItsYourAhmed1 @ashraf789 is this issue solved?

**Comment by ashraf789** [comment]
No it's still remain. I could not found why the error giving.

Now I am busy with my office work. 

I made the library source code as public. so if you want to contribute you can solve this problem.

**Comment by akyzi007** [comment]
okay I am on it.

**Comment by khashayar-k** [comment]
hi @ashraf789 did you find any solutions ?? i tried everything but still not working on android 10

**Comment by coderzstas** [comment]
i have a similar trouble but with another vpn app . try to change this to 28

    compileSdkVersion 29
    buildToolsVersion "29.0.2"
    targetSdkVersion 29

**Comment by khashayar-k** [comment]
Hi @coderzstas thanks for the solution i will try it and report back

**Comment by khashayar-k** [comment]
wow! thanks @coderzstas it worked best of regards
just change the build.gradle(app) to this and it will work on android 10
```
 android {
    compileSdkVersion 28
    buildToolsVersion "28.0.2"
    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 28
```

**Comment by ashraf789** [comment]
Awesome,
Thanks to @coderzstas and @khashayar-k for your contribution.

**Comment by coderzstas** [comment]
Well nice :)

**Comment by istiak101** [comment]
I think due to changes of behaviour from api 29+ this happens
https://developer.android.com/about/versions/10/behavior-changes-10

**Comment by YuAmbrose** [comment]
> 我认为由于来自api 29+的行为更改，因此发生了
> https://developer.android.com/about/versions/10/behavior-changes-10

How to solve this problem in API 29, do you have a good solution?

**Comment by ashraf789** [comment]
Sorry, I don't have, currently working with the different techniques :'( .

**Comment by GHOST78600007** [comment]
> > 我认为由于来自api 29+的行为更改，因此发生了
> > https://developer.android.com/about/versions/10/behavior-changes-10
> 
> How to solve this problem in API 29, do you have a good solution?

Did you solve the problem ? When I use API 29 it does not work .. please help

**Comment by istiak101** [comment]
> > > 我认为由于来自api 29+的行为更改，因此发生了
> > > https://developer.android.com/about/versions/10/behavior-changes-10
> > 
> > 
> > How to solve this problem in API 29, do you have a good solution?
> 
> Did you solve the problem ? When I use API 29 it does not work .. please help

If you want to demotivate a FOSS developer by giving a thumbs down you should rather solve it yourself.

**Comment by GHOST78600007** [comment]
> > > > 我认为由于来自api 29+的行为更改，因此发生了
> > > > https://developer.android.com/about/versions/10/behavior-changes-10
> > > 
> > > 
> > > How to solve this problem in API 29, do you have a good solution?
> > 
> > 
> > Did you solve the problem ? When I use API 29 it does not work .. please help
> 
> If you want to demotivate a FOSS developer by giving a thumbs down you should rather solve it yourself.

Sorry for misunderstanding, it was a mistake, I apologise, but ... 
Do you have any solution ... Please tell me 😭
