### ISSUE TITLE
android app bundle is not working 

### ISSUE THREAD

**Issue by Deepanshusuman** [ashraf789/Cake-VPN#41]
i have added library gradle file 
splits {
            abi {
                enable = true
                reset()
                include("x86", "x86_64", "armeabi-v7a", "arm64-v8a")
                universalApk  = true
            }
        }

but it is not working 
please update or help

**Comment by ashraf789** [comment]
I am sorry, I could not help you to generate your signed APK. 
I hope you could fix it by yourself

Thanks 
Ashraf
