### ISSUE TITLE
My ovpn file doesn't have username and password. How do I connect to it?

### ISSUE THREAD

**Issue by badoyg** [ashraf789/Cake-VPN#42]
My ovpn file doesn't have username and password. How do I connect to it?

**Comment by ashraf789** [comment]
set null if you do not have a user name and password.

![image](https://user-images.githubusercontent.com/13873490/89699642-79122780-d952-11ea-9de0-27f13e7a464d.png)

**Comment by badoyg** [comment]
It did not work. I still can't Connect. Try it

**Comment by badoyg** [comment]
Try it Ashraf And tell me solution thanks

**Comment by ashraf789** [comment]
Well in that case use empty instead of null. I hope it will solve your problem.
![image](https://user-images.githubusercontent.com/13873490/89718792-18372d80-d9ec-11ea-86e8-598c929c8a01.png)

**Comment by badoyg** [comment]
I just tried it. It did not work. Please test it. Thanks

**Comment by ashraf789** [comment]
Yes, I just checked it again it's working fine. 
1. Go to your ManActivity.java 
2. Find out japan.ovpn make username and password empty then try again.

**Comment by ashraf789** [comment]
I also tried with null and it's working fine. So I think there could be problem with your ovpn file.

**Comment by BilalAsif25** [comment]
Hi Ashraf, i also have the same problem if i download an ovpn file that doenst have username or pw, providing null and empty string also not working, it just stuck on connecting, i downloaded us ovpn file from here for testing purpose can you plz elaborate the issue?

https://www.ovpn.com/en/configurations

**Comment by BilalAsif25** [comment]
![Capture1](https://user-images.githubusercontent.com/33984559/91658399-4ab2e280-eae1-11ea-9cea-8deb616cadb6.PNG)
![Capture2](https://user-images.githubusercontent.com/33984559/91658402-4c7ca600-eae1-11ea-8b35-e64515c25e85.PNG)

**Comment by ashraf789** [comment]
@BilalAsif25 
I think **auth-user-pass** means that the configuration requires a user name password.
Could you please check our configuration by the openvpn client app.
https://play.google.com/store/apps/details?id=net.openvpn.openvpn&hl=en

**Comment by adnanamin69** [comment]
@ashraf789 @BilalAsif25 did you guys find any solution
