### ISSUE TITLE
Closing/hiding notification

### ISSUE THREAD

**Issue by maci3k90** [ashraf789/Cake-VPN#43]
Hello. I just wanted to stop all processes and close activities when disconnect button was clicked. I was trying different techniques of closing/killing services, threads and activities from code, but notification is still visible. Do you have any suggestions? Thank you in advance.

BTW. Great work with Cake VPN. It really helps to start working with library.

**Comment by ashraf789** [comment]
You can cancel notification like this 
https://github.com/ashraf789/Cake-VPN/blob/master/vpnLib/src/main/java/de/blinkt/openvpn/core/OpenVPNService.java#L373

**Comment by maci3k90** [comment]
Thanks for the tip. cancelAll() did the trick.
