### ISSUE TITLE
it doesn't connect after changing the TargetSdkVersion to 29/30

### ISSUE THREAD

**Issue by wdtheprovider** [ashraf789/Cake-VPN#44]
after changing the TargetSdkVersion to 29/30 the vpn doesnt connect it goes straight to disconnect

**Comment by ashraf789** [comment]
Sorry, I didn't understand. currently, the target SDK is 30 and it's working fine.
Please write more details about your issue. 
![image](https://user-images.githubusercontent.com/13873490/90350897-b9675900-e068-11ea-9089-219291a0be78.png)

Thanks

**Comment by wdtheprovider** [comment]
I'm sorry. But i think this images can explain better. On the sdk30 im unable to connect.
![sdk30](https://user-images.githubusercontent.com/49024101/90390747-2e985580-e08c-11ea-83a8-0c368d97d6fd.JPG)

Then on sdk28, it does connect.
![sdk28](https://user-images.githubusercontent.com/49024101/90390753-31934600-e08c-11ea-9b75-fbd4f5f767b4.JPG)

**Comment by ashraf789** [comment]
![image](https://user-images.githubusercontent.com/13873490/90634793-7c5eba80-e252-11ea-8579-2f402e33aea6.png)

**Comment by ashraf789** [comment]
Please delete your old app then install it again.

**Comment by wdtheprovider** [comment]
Thank you for your reply and solution. i updated to sdk30 and tested in a different phone (samsung s3)  and it worked. 
But when i test it on Huawei smartphones, it doesnt connect, i tested it on Huawei Honor 8x, Huawei Y5, Huawei p9 with SDK 29/30

only SDK 28 works on Huawei devices.

**Comment by ashraf789** [comment]
Thank you for the details. 
I do not have those devices. I am also a samsung user. 
But If I find out the error I will try to solve it.

**Comment by Ikram168** [comment]
Its bundle after uploading not connect

**Comment by gulabsagevadiya** [comment]
Yes Same As Ikram168 not working after creating bundle for play store. same error as above.  working fine in apk.  also this is great help for vpn lib user guide.

**Comment by ashraf789** [comment]
https://github.com/ashraf789/Cake-VPN/issues/81
