### ISSUE TITLE
Dismiss notification on disconnect

### ISSUE THREAD

**Issue by inabdev30** [ashraf789/Cake-VPN#47]
Unable to dismiss foreground service notification on the VPN disconnect. Even after closing the app or disconnect VPN notification remains there (Check screenshots). Can you please help me to solve it. I want the notification to dismiss as I disconnect the VPN. Thank you.
![Screenshot_20200831-165704](https://user-images.githubusercontent.com/51774125/91717655-5e2a8000-ebab-11ea-83ca-4d5cf435066f.png)
![Screenshot_20200831-165709](https://user-images.githubusercontent.com/51774125/91717670-62ef3400-ebab-11ea-99e7-4ff0a7d27bd1.png)

**Comment by ashraf789** [comment]
@inabdev30 
Please write more details about your device model, error log, etc.

**Comment by Natkarock** [comment]
> @inabdev30
> Please write more details about your device model, error log, etc.

Model: Xiaomi Redmi Note 2, 23 SDK, notification not closed, but in log i have: **04-15 16:01:13.971 18301-18715/com.lerta.vpndiler I/OpenVPN: zOpenVPN process exited
04-15 16:01:14.012 18301-18715/com.lerta.vpndiler I/OpenVPN: Exiting**  and i see, that vpn is closed.But I still have a sticky notification in status bar.

**Comment by ashraf789** [comment]
> device model, error log, etc.

Did you face the same error from the cakeVPN app?

**Comment by Natkarock** [comment]
Yes, i have

**Comment by Natkarock** [comment]
> > device model, error log, etc.
> 
> Did you face the same error from the cakeVPN app?

Yes, i have

**Comment by ashraf789** [comment]
Thank you for the information. currently, I don't have the above device to test and fix. 
so I can't fix it soon, will fix it later.

**Comment by Natkarock** [comment]
> Thank you for the information. currently, I don't have the above device to test and fix.
> so I can't fix it soon, will fix it later.

I found a problem in OpenVPNService. You should remove this block 
`
else {
            // If earlier version channel ID is not used
            // https://developer.android.com/reference/android/support/v4/app/NotificationCompat.Builder.html#NotificationCompat.Builder(android.content.Context)
            channel = "";
        }
`

We have a channel name in this function and shouldn't set empty string to it

**Comment by ashraf789** [comment]
@Natkarock could you please make PR request?

**Comment by Natkarock** [comment]
> @Natkarock could you please make a PR request?

It's done #72
