### ISSUE TITLE
Vpn is not connecting on Pixel (Android 10) via .aab file

### ISSUE THREAD

**Issue by sandeep9094** [ashraf789/Cake-VPN#49]
On installing application from generated .aab file

**Comment by ashraf789** [comment]
Hello,
Did you try with a new ovpn file?

please add more detailed information.

**Comment by sandeep9094** [comment]
I have changed Ovpn file. Still gets error.
App runs fine in debug mode.
Getting exception

```
2020-09-27 15:14:52.189 8796-8952/? I/OpenVPN: Starting openvpn
2020-09-27 15:14:52.194 8796-8952/? E/OpenVPN: OpenVPNThread Got java.lang.NullPointerException: Attempt to invoke virtual method 'void java.lang.Process.destroy()' on a null object reference
2020-09-27 15:14:52.211 8796-8952/? I/OpenVPN: Exiting
```
And I have updated vpnLib module with updated gradle version to target SDK 30

**Comment by ashraf789** [comment]
"And I have updated vpnLib module with updated gradle version to target SDK 30"
Sorry, I think there is some problem when you update the vpnLib module. 

The current source code is fine with target SDK 30

**Comment by wasi92** [comment]
> "And I have updated vpnLib module with updated gradle version to target SDK 30"
> Sorry, I think there is some problem when you update the vpnLib module.
> 
> The current source code is fine with target SDK 30

how to change pakage name plz help me

**Comment by sandeep9094** [comment]
@ashraf789 Exception 
OpenVPN process: java.io.IOException: Cannot run program "/data/app/com.example.vpndemo-SIE7WtmxaZXy7pblHI4nEA==/lib/arm64/libovpnexec.so": error=2, No such file or directory

**Comment by sandeep9094** [comment]
@wasi92 Change package open app > java > module app (com.example.appname)
Go to show option menu in project structure > un-select **Compack Middle Packages** 
Then open options on which module want to rename (example) : Go to **refractor > rename> rename package name**

**Comment by Deepanshusuman** [comment]
It will not work with aab file try installing apk file

**Comment by sandeep9094** [comment]
@Deepanshusuman why vpn doesn't work with .aab file and run fines with .apk

**Comment by Deepanshusuman** [comment]
idk because  of some .so located in 
https://github.com/ashraf789/Cake-VPN/tree/master/vpnLib/src/main/assets
https://github.com/ashraf789/Cake-VPN/tree/master/vpnLib/src/main/jniLibs

 file which get left behind when comipling to .aab .
i have only get this much

**Comment by AmanArora1987** [comment]
> probabally because of some .so located in
> https://github.com/ashraf789/Cake-VPN/tree/master/vpnLib/src/main/assets
> https://github.com/ashraf789/Cake-VPN/tree/master/vpnLib/src/main/jniLibs
> 
> file which get left behind when comipling to .aab .
> i have only get this much

Since there is no native dependency to run in vpn library, Is there any way we can add native dependencies to library module?

**Comment by Deepanshusuman** [comment]
have a look
https://developer.android.com/guide/topics/connectivity/vpn

**Comment by techylax** [comment]
> It will not work with aab file try installing apk file

why it won't connect .?

**Comment by birdeveloper** [comment]
Hello,
this error occurs inside the startOpenVPNThreadArgs function.
it originates from this line of code: mProcess = pb.start ();

ProcessBuilder kills or does not accept proccesses when converted to aab.

That's why I signed my application with apk and published it. It is working now, no problem.

https://play.google.com/store/apps/details?id=com.vpngalaxy.app

**Comment by Deepanshusuman** [comment]
> Hello I solved this problem,
> this error occurs inside the startOpenVPNThreadArgs function.
> it originates from this line of code: mProcess = pb.start ();
> 
> ProcessBuilder kills or does not accept proccesses when converted to aab.
> 
> That's why I signed my application with apk and published it. It is working now, no problem.
> 
> https://play.google.com/store/apps/details?id=com.vpngalaxy.app

Please make a pull request

**Comment by birdeveloper** [comment]
> > Hello I solved this problem,
> > this error occurs inside the startOpenVPNThreadArgs function.
> > it originates from this line of code: mProcess = pb.start ();
> > ProcessBuilder kills or does not accept proccesses when converted to aab.
> > That's why I signed my application with apk and published it. It is working now, no problem.
> > https://play.google.com/store/apps/details?id=com.vpngalaxy.app
> 
> I have a question that why is your app is size of 50 mb
> Please make a pull request

The files and animations inside my application take up this much space.
<a href="https://hizliresim.com/61fHs0">
    <img src="https://i.hizliresim.com/61fHs0.png" alt="ScreenShot" >
  </a>

**Comment by Deepanshusuman** [comment]
> > > Hello I solved this problem,
> > > this error occurs inside the startOpenVPNThreadArgs function.
> > > it originates from this line of code: mProcess = pb.start ();
> > > ProcessBuilder kills or does not accept proccesses when converted to aab.
> > > That's why I signed my application with apk and published it. It is working now, no problem.
> > > https://play.google.com/store/apps/details?id=com.vpngalaxy.app
> > 
> > 
> > I have a question that why is your app is size of 50 mb
> > Please make a pull request
> 
> The files and animations inside my application take up this much space.
> [ ![ScreenShot](https://camo.githubusercontent.com/8ee92301ad6b53e4bd83d2c690eab72e0b8f2112/68747470733a2f2f692e68697a6c69726573696d2e636f6d2f3631664873302e706e67) ](https://hizliresim.com/61fHs0)

Please make a pull request or share the code to change

**Comment by assilMekki** [comment]
> > > > Hello I solved this problem,
> > > > this error occurs inside the startOpenVPNThreadArgs function.
> > > > it originates from this line of code: mProcess = pb.start ();
> > > > ProcessBuilder kills or does not accept proccesses when converted to aab.
> > > > That's why I signed my application with apk and published it. It is working now, no problem.
> > > > https://play.google.com/store/apps/details?id=com.vpngalaxy.app
> > > 
> > > 
> > > I have a question that why is your app is size of 50 mb
> > > Please make a pull request
> > 
> > 
> > The files and animations inside my application take up this much space.
> > [ ![ScreenShot](https://camo.githubusercontent.com/8ee92301ad6b53e4bd83d2c690eab72e0b8f2112/68747470733a2f2f692e68697a6c69726573696d2e636f6d2f3631664873302e706e67) ](https://hizliresim.com/61fHs0)
> 
> Please make a pull request or share the code to change

on which repo ?

**Comment by Deepanshusuman** [comment]
> > > > > Hello I solved this problem,
> > > > > this error occurs inside the startOpenVPNThreadArgs function.
> > > > > it originates from this line of code: mProcess = pb.start ();
> > > > > ProcessBuilder kills or does not accept proccesses when converted to aab.
> > > > > That's why I signed my application with apk and published it. It is working now, no problem.
> > > > > https://play.google.com/store/apps/details?id=com.vpngalaxy.app
> > > > 
> > > > 
> > > > I have a question that why is your app is size of 50 mb
> > > > Please make a pull request
> > > 
> > > 
> > > The files and animations inside my application take up this much space.
> > > [ ![ScreenShot](https://camo.githubusercontent.com/8ee92301ad6b53e4bd83d2c690eab72e0b8f2112/68747470733a2f2f692e68697a6c69726573696d2e636f6d2f3631664873302e706e67) ](https://hizliresim.com/61fHs0)
> > 
> > 
> > Please make a pull request or share the code to change
> 
> on which repo ?

This one

**Comment by Deepanshusuman** [comment]
Please update code

**Comment by Deepanshusuman** [comment]
i thought it is abb but it is apk

**Comment by Al3xPaladino** [comment]
> @ashraf789 Exception
> OpenVPN process: java.io.IOException: Cannot run program "/data/app/com.example.vpndemo-SIE7WtmxaZXy7pblHI4nEA==/lib/arm64/libovpnexec.so": error=2, No such file or directory

java.io.IOException: Cannot run program "/data/app/com.example.appreasyboost-8nvCVP3K3CODxJB-jPCycg==/lib/arm64/libovpnexec.so": error=2, No such file or directory

How can i solve?

**Comment by dlukashanets** [comment]
Add next property to file gradle.properties, should help
`android.bundle.enableUncompressedNativeLibs=false`

**Comment by Deepanshusuman** [comment]
@dlukashanets 
it is working 

but you can see no saving 
![Screenshot_1](https://user-images.githubusercontent.com/25487423/101996006-b584d400-3cf4-11eb-8a7a-d0b262bd8d0d.png)

**Comment by Deepanshusuman** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/25487423/101996175-106afb00-3cf6-11eb-8ce0-6f5e33e25940.png)
ok i got

**Comment by Natkarock** [comment]
> @ashraf789 Exception
> OpenVPN process: java.io.IOException: Cannot run program "/data/app/com.example.vpndemo-SIE7WtmxaZXy7pblHI4nEA==/lib/arm64/libovpnexec.so": error=2, No such file or directory

How you solve this problem?

**Comment by Natkarock** [comment]
> > @ashraf789 Exception
> > OpenVPN process: java.io.IOException: Cannot run program "/data/app/com.example.vpndemo-SIE7WtmxaZXy7pblHI4nEA==/lib/arm64/libovpnexec.so": error=2, No such file or directory
> 
> java.io.IOException: Cannot run program "/data/app/com.example.appreasyboost-8nvCVP3K3CODxJB-jPCycg==/lib/arm64/libovpnexec.so": error=2, No such file or directory
> 
> How can i solve?
> Please help me.

How you solved this problem?

**Comment by ummersiddique** [comment]
Hello I solved this problem.

Thanks to [this answer](https://github.com/ashraf789/Cake-VPN/issues/49#issuecomment-735163848)
