### ISSUE TITLE
problem with ovpn config files that have tls-crypt

### ISSUE THREAD

**Issue by khashayar-k** [ashraf789/Cake-VPN#5]
Hi nice job, but there is a problem if i use a ovpn config file that have tls-crypt in it it wont work is there any solution to solve that??

**Comment by ashraf789** [comment]
Did you use tls-crypt on UDP or TCP protocol?

**Comment by khashayar-k** [comment]
tried both UDP and TCP

**Comment by khashayar-k** [comment]
i was thinking maybe i could change my server.conf from tls-crypt to tls-auth but i dont know how

**Comment by ashraf789** [comment]
Sorry i didn,t work with server configuration

**Comment by khashayar-k** [comment]
after searching i figured out that openvpn connect does not support tls-crypt and for anyone with this issue just remove any line with tls in your /etc/openvpn/server.conf
and then remove the tls-crypt key in your client.ovpn file it will work
