### ISSUE TITLE
Open VPN over SSL

### ISSUE THREAD

**Issue by anthony143** [ashraf789/Cake-VPN#52]
Hi,

I really appreciate your work. Using this, I learned a lot. I hope you will add more features on this project. Have you heared HTTP Injector? Can you create a tutorial om how to compiled ICS-OpenVPN? You can create a Youtube channel and I am willing to subsceibe.

Thanks

**Comment by ashraf789** [comment]
Sorry, didn't heard about HTTP injector
you can follow the instruction to compile ics-opnvpn
https://github.com/schwabe/ics-openvpn/blob/master/doc/README.txt
