### ISSUE TITLE
Exclude app from using VPN

### ISSUE THREAD

**Issue by anyms** [ashraf789/Cake-VPN#55]
How can I exclude the VPN app itself to send the requests through the VPN? I am using admob with my VPN app when I connect to a VPN for example if I connect to a Korean VPN the ads are showing in korean. I think it could affect my admob earnings.

Is there any way to exclude the app by package name?

I was looking through the VPN source code, I found this class `ExternalAppDatabase` which contains methods `addApp` and `isAllowed` I tried with a condition if the package name is my app then return false or not add, but it's not working.

**Comment by ashraf789** [comment]
Hello, 
Inside the ExternalAppDatabase class, the addApp method and admob ads are two different things. Also, I think what you wanting that's near impossible.

When you connect your VPN app with a VPN server then the app makes a secure tunnel with the server. any data transfer from your app goes through the server. that's means when you connect with a Korean server and access Google in that case Google responds back to your Korean server, not to you. 

I hope you understand.
Thanks

**Comment by Deepanshusuman** [comment]
on OpenVPNService.java
after line number 

https://github.com/ashraf789/Cake-VPN/blob/5a5b1b26a72eb402fbf7e97b24742f53f6c8c674/vpnLib/src/main/java/de/blinkt/openvpn/core/OpenVPNService.java#L797

add this to your app

if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            try {
                builder.addDisallowedApplication("com.android.chrome");
            } catch (Exception e) {

            }
        }

**Comment by anyms** [comment]
> on OpenVPNService.java
> after line number
> 
> https://github.com/ashraf789/Cake-VPN/blob/5a5b1b26a72eb402fbf7e97b24742f53f6c8c674/vpnLib/src/main/java/de/blinkt/openvpn/core/OpenVPNService.java#L797
> 
> add this to your app
> 
> if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
> try {
> builder.addDisallowedApplication("com.android.chrome");
> } catch (Exception e) {
> 
> ```
>         }
>     }
> ```

Thanks a lot. It worked for me.
