### ISSUE TITLE
VPN Not Connecting after app Published in play store

### ISSUE THREAD

**Issue by gnanesh023** [ashraf789/Cake-VPN#57]
app was working on testing so i published to play store , after that i download the app from  play store  , app was opening properly but not connecting to vpn , when i tap connect button but no response..
showing connecting for 2 sec then hide , nothing happens

**Comment by ashraf789** [comment]
Did you get any error messages?

**Comment by Deepanshusuman** [comment]
try publisging the apk file

**Comment by Deepanshusuman** [comment]
[Check thsi](https://github.com/ashraf789/Cake-VPN/issues/49#issuecomment-735163848``)

**Comment by gnanesh023** [comment]
now working, and I downloaded config files from vpnget.net , those files are slow nnd expires soon , can you suggest me any other free ovpn files sites?

, thank you ,

**Comment by ashraf789** [comment]
You can try this https://www.freeopenvpn.org/en/
But for production, you should set up your won server.

Please close the issue if your problem solved.
Thanks.
