### ISSUE TITLE
Am i connecting ?

### ISSUE THREAD

**Issue by harunkaraca** [ashraf789/Cake-VPN#63]
Hi, i did all steps what you say. I see the connected log. Which i can see in and out bytes. But I am entering https://www.whatismyip.com/ through google chorme. My ip is still the same. Why i can't connect through my vpn.

**Comment by ashraf789** [comment]
1. Make sure you are connected with a VPN server 
2. Open https://www.whatismyip.com/ on incognito mode.

This app is live on the google play store you may try to install the live app.
https://play.google.com/store/apps/details?id=com.ashraf789.cakevpn

**Comment by harunkaraca** [comment]
You're right. I signup on openvpncloud. And create a hosts. I see the my connection on openvpncloud panel. But openvpn does not allowed me. I think i am doing wrong. I am newbie :). Thank you for your sharing code with community 👍
