### ISSUE TITLE
bypass-dns dos not work

### ISSUE THREAD

**Issue by cnsms** [ashraf789/Cake-VPN#64]
bypass-dns
it in .ovpn file

**Comment by cnsms** [comment]
03-07 18:11:07.433 7587-7625/com.lazycoder.cakevpn D/ViewContentFactory: initViewContentFetcherClass
03-07 18:11:07.434 7587-7625/com.lazycoder.cakevpn D/ViewContentFactory: getInterceptorPackageInfo
03-07 18:11:07.435 7587-7625/com.lazycoder.cakevpn D/ViewContentFactory: getInitialApplication took 2ms
03-07 18:11:07.435 7587-7625/com.lazycoder.cakevpn D/ViewContentFactory: packageInfo.packageName: com.miui.catcherpatch
03-07 18:11:07.442 7587-7625/com.lazycoder.cakevpn D/ViewContentFactory: initViewContentFetcherClass took 9ms
03-07 18:11:07.443 7587-7625/com.lazycoder.cakevpn D/ViewContentFactory: createInterceptor took 9ms
03-07 18:11:07.618 7587-7587/com.lazycoder.cakevpn W/Glide: Failed to find GeneratedAppGlideModule. You should include an annotationProcessor compile dependency on com.github.bumptech.glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignored
03-07 18:11:07.657 7587-7587/com.lazycoder.cakevpn D/openvpn: Loading openvpn native library $id$ compiled on Jun 23 2020 13:36:40
03-07 18:11:26.698 7587-7587/com.lazycoder.cakevpn D/OpenVpnApi: startVpnInternal: ==============de.blinkt.openvpn.core.ConfigParser@405c465
    converted Profile
03-07 18:11:26.854 7587-7856/com.lazycoder.cakevpn I/OpenVPN: Starting openvpn
03-07 18:11:26.899 7587-7856/com.lazycoder.cakevpn I/OpenVPN: OpenVPN process exited
03-07 18:11:26.913 7587-7856/com.lazycoder.cakevpn I/OpenVPN: Exiting

**Comment by cnsms** [comment]
my .ovpn file 

client
dev-type tun
dev tun
proto udp
tun-mtu 1400
cipher BF-CBC
comp-lzo
remote 1*7.2*0.1*9.*3 1194
resolv-retry infinite
nobind
persist-key
persist-tun
verb 3
auth-user-pass
bypass-dns

**Comment by cnsms** [comment]
if i delete "bypass-dns" it works,but my ip is not change

**Comment by ashraf789** [comment]
Hello,
I think your ovpn file has problem.  you may try the free ovpn file to test your app.
https://www.vpngate.net/en/

**Comment by cnsms** [comment]
thanks,I will try
