### ISSUE TITLE
Can I route device traffic via LTE or WiFi based on app usage?

### ISSUE THREAD

**Issue by amol-d** [ashraf789/Cake-VPN#65]
Can I use [ConnectivityManager.requestNetwork()](https://developer.android.com/reference/android/net/ConnectivityManager#requestNetwork(android.net.NetworkRequest,%20android.net.ConnectivityManager.NetworkCallback)) capability in conjunction with VpnService to route network traffic via LTE or WiFi?

**Comment by amol-d** [comment]
Or can we use [VpnService.Builder().SetUnderlyingNetwork()](https://developer.android.com/reference/android/net/VpnService.Builder#setUnderlyingNetworks(android.net.Network[])) to achieve same?

**Comment by ashraf789** [comment]
Hello,
I am sorry, I am not sure about your request.

**Comment by amol-d** [comment]
Hello,
Basically I want my vpn to use cellular network even if device is connected to WiFi network.
 I see there is method available "VpnService.Builder().SetUnderlyingNetwork()" which can be further explored.
You can refer related discussion [here](https://github.com/schwabe/ics-openvpn/issues/449)

**Comment by ashraf789** [comment]
Hello,
Please follow your refer link discussion. I have no idea of your requested function. 
And I don't have enough time to research it for you.

I am sorry, thank you.
