### ISSUE TITLE
how to add kill switch

### ISSUE THREAD

**Issue by Deepanshusuman** [ashraf789/Cake-VPN#68]

**Comment by ashraf789** [comment]
Please add details about your issue. 
Thanks

**Comment by Deepanshusuman** [comment]
like turbo vpn

**Comment by ashraf789** [comment]
Could you please give me a screenshot? currently, the disconnect button kills the VPN service.

**Comment by rajatkumardhamija** [comment]
Hi did you figure out how to add kill switch in open vpn?
