### ISSUE TITLE
Very slow connection

### ISSUE THREAD

**Issue by SlonGL** [ashraf789/Cake-VPN#75]
Hello.

Once connected, the speed drops very hard. 50-80 Mbps without VPN and 0.05 - 1.0 with VPN.
Is it because of the features of OpenVPN or do I have an incorrectly configured server? I have read in several places that OpenVPN cuts speed precisely in Android. The same server in my iOS application gives a speed of 30-40 Mbps on a mobile connection.

Thank you in advance for your answer.

**Comment by ashraf789** [comment]
Yes, VPN is slow but  0.05 - 1.0 is too low. VPN speed depends on your server location, speed, number of simultaneous users, etc.
In the live app, you may test the different server and their speed. 
https://play.google.com/store/apps/details?id=com.ashraf789.cakevpn

**Comment by ashraf789** [comment]
![Screenshot_20210617-230932_Chrome](https://user-images.githubusercontent.com/13873490/122435780-7cd6f780-cfc2-11eb-840c-83681ee3e149.jpg)
![Screenshot_20210617-231553_Chrome](https://user-images.githubusercontent.com/13873490/122435786-7e082480-cfc2-11eb-9315-159c878ee7a1.jpg)
![Screenshot_20210617-230906_Chrome](https://user-images.githubusercontent.com/13873490/122435866-92e4b800-cfc2-11eb-9f0d-3d908cb8476b.jpg)

**Comment by SlonGL** [comment]
I use the same server I use for the iOS app. And the devices are connected from the same network. The speed difference is ten or more times. Indeed, we should try with other servers, and then we will understand this problem of Android or server.

This is what I read on the OpenVPN Support Forum on the issue of speed drop.
------------
Why doesn't the app support tap-style tunnels?
A: The Android VPN API supports only tun-style tunnels at the moment. This is a limitation of the Android platform. If you try to connect a profile that uses a tap-based tunnel, you will get an error that only layer 3 tunnels are currently supported.
If you really want to see tap-style tunnels supported in OpenVPN Connect, we would encourage you to contact the Google Android team and ask that the VpnService API be extended to allow this. Without such changes to the VpnService API, it is not possible for non-root apps such as OpenVPN Connect to support tap-style tunnels.
------------

Thank you for your answer. I’ll try other servers to understand the pattern.

**Comment by Deepanshusuman** [comment]
you can get 40-70 Mbps speed on VPN also
