### ISSUE TITLE
.ovpn file username and password query

### ISSUE THREAD

**Issue by codewithshubh** [ashraf789/Cake-VPN#76]
From where I will get the username and password for the .ovpn file?

**Comment by ashraf789** [comment]
Hello,
When you set up your open VPN server you can set a username and password to access the VPN. 
For this app, I used some free ovpn file from https://www.vpngate.net/en/
As the .ovpn file is public they didn't set a username and password to authenticate.

**Comment by codewithshubh** [comment]
nd how to get the value of ip address to which the app is connect.. If I want to show that as well in the application?

**Comment by ashraf789** [comment]
.ovpn file IP is fixed you may display that IP.

**Comment by ashraf789** [comment]
![image](https://user-images.githubusercontent.com/13873490/123034672-23ccf080-d414-11eb-968c-1d988dc503f6.png)

**Comment by ashraf789** [comment]
![image](https://user-images.githubusercontent.com/13873490/123034804-6ee70380-d414-11eb-8762-ef044f972fff.png)
https://www.ipvoid.com/find-website-ip/

**Comment by codewithshubh** [comment]
Great! Thank you so much for your answer. One last question.. The OpenVPN library which you are using, how to import that library from its official Github repo. As I am a bit confused because I didn't find any library folder in that repo like yours.. But files under the src folder are the same.

My main issue is that I am not able to import the OpenVPN module/library from its official repo (https://github.com/schwabe/ics-openvpn) into my newly created android studio project. If you could help me with this, It would be so grateful of you.

**Comment by ashraf789** [comment]
https://github.com/ashraf789/Cake-VPN/issues/67
