### ISSUE TITLE
How did you create an opvn configuration.

### ISSUE THREAD

**Issue by KaustubhPatange** [ashraf789/Cake-VPN#77]
You mentioned the link to https://www.vpngate.net/en but there is no option to download the configuration. So this mean do we have to create it manually.

After looking I found some [notes](https://openvpn.net/community-resources/creating-configuration-files-for-server-and-clients/), does this help?

**Comment by ashraf789** [comment]
You can download from https://www.vpngate.net/en like this 
![image](https://user-images.githubusercontent.com/13873490/123991977-633ba400-d9f5-11eb-9641-53b7b7042b40.png)

**Comment by ashraf789** [comment]
That's good (y)
