### ISSUE TITLE
How to set Auto reconnect when network is changed

### ISSUE THREAD

**Issue by NomanAziz51** [ashraf789/Cake-VPN#80]
Hi, the app doesn't reconnect when I switch WiFi to network data.

**Comment by ashraf789** [comment]
Could you please try this app
https://play.google.com/store/apps/details?id=com.ashraf789.cakevpn

If still the same problem please let me know more details about your device.
Thanks

**Comment by NomanAziz51** [comment]
I build my own app using your vpn client. Everything is working fine but the issues is when i switch my network it disconnect and doesn't reconnect.

**Comment by ashraf789** [comment]
since this app is working fine, I am not sure about your problem. if your app is open source let me share the link. 
I may have a look.

**Comment by NomanAziz51** [comment]
https://drive.google.com/file/d/1oPEMfzGxcPnS4HNcOdE8unj_nfrsF8QC/view?usp=drivesdk

**Comment by ashraf789** [comment]
I mean the source code, not apk.

**Comment by NomanAziz51** [comment]
Send me your email

**Comment by ashraf789** [comment]
Ashrafswe789@gmail.com

**Comment by NomanAziz51** [comment]
I have added you to in my repository kindly please help

**Comment by ashraf789** [comment]
I have reviewed your source code. you wrote your app on Kotlin I am not familiar with kotlin secondly, you have updated the vpn lib source code. probably you make mistake there.
