### ISSUE TITLE
Working Fine In Apk But When We Create Bundle For Play store then it is not working

### ISSUE THREAD

**Issue by gulabsagevadiya** [ashraf789/Cake-VPN#81]
`E/OpenVPN: OpenVPNThread Got java.lang.NullPointerException: Attempt to invoke virtual method 'void java.lang.Process.destroy()' on a null object reference`

This Error Comes 
I have added 
`android:extractNativeLibs="true"
tools:replace="android:extractNativeLibs"`
in manifest but still getting this null Object exception
also bundle file is around 12 MB but on play store it shows 4 MB size App

**Comment by ashraf789** [comment]
Hello, 
Did you try with gradle.properties
android.bundle.enableUncompressedNativeLibs=false

https://github.com/ashraf789/Cake-VPN/blob/master/gradle.properties
