### ISSUE TITLE
How to get ip address as boardCast receiver?

### ISSUE THREAD

**Issue by AndroXStudiO** [ashraf789/Cake-VPN#82]
How to get ip address as boardCast receiver?

**Comment by ashraf789** [comment]
Hello,
Please write more details about your issue. 

Thanks.

**Comment by AndroXStudiO** [comment]
I want to know, which is my connection id address and i want to show this ip address in textView

**Comment by ashraf789** [comment]
This feature current we don't have and also the main library doesn't have. I am not sure when I will work on this feature. 
If you want you to need to do it by yourself. 

Thanks
