### ISSUE TITLE
vpnThread.stop(); crash app

### ISSUE THREAD

**Issue by AndroXStudiO** [ashraf789/Cake-VPN#83]
Crash app when call vpnThread.stop();
Please help me

**Comment by ashraf789** [comment]
I am not sure about your issue. please include the full error message and device details.

Also, please check this code.
https://github.com/ashraf789/Cake-VPN/blob/master/app/src/main/java/com/lazycoder/cakevpn/view/MainFragment.java#L119

**Comment by AndroXStudiO** [comment]
![Uploading Screenshot_2021-08-23-11-54-42-30_3b217fd44a99af3c3bbd4c143df87222.jpg…]()

**Comment by AndroXStudiO** [comment]
See this

**Comment by AndroXStudiO** [comment]
![Uploading Screenshot_2021-08-23-10-48-56-98_5ebabe8265cc2e6142c92e9357107d23.jpg…]()

**Comment by ashraf789** [comment]
Can't view your uploaded file.

**Comment by AndroXStudiO** [comment]
You from Bangladesh?

**Comment by ashraf789** [comment]
Yes, but currently live in Vietnam.

**Comment by AndroXStudiO** [comment]
Bro..ovpn file thik moto kaj kore na? Ami android app e kaj korCilam....just Japan ovpn ta kaj kore...onno gulo just connecting likha hoi...connected hoi na

**Comment by ashraf789** [comment]
The Ovpn files are some example files to test the APP. You need to build your own ovpn server. 
I think this issue you already solved if so please close it if no please let me know the details of your error.
Thanks

**Comment by AndroXStudiO** [comment]
Brother can you send me your Facebook link.

Or openVpn library as jar file or as a  aar file?

I need this very much...please

**Comment by ashraf789** [comment]
Please follow these instructions to export the library 
https://developer.android.com/studio/projects/android-library
https://stackoverflow.com/questions/16763090/how-to-export-library-to-jar-in-android-studio

https://www.facebook.com/sashraf789/

Thanks
