### ISSUE TITLE
OpenVPN doesn't work after changing the TargetSdkVersion to 29/30

### ISSUE THREAD

**Issue by newfuture33** [ashraf789/Cake-VPN#91]
if targetSDKVersion is 28, works fine on my android 10.0.
but if I changed TargetSDKVersion to 29/30, can't connect.

**Comment by newfuture33** [comment]
![image](https://user-images.githubusercontent.com/34529419/135767059-4bf34a24-1860-4a7b-90e4-96d61e3d8240.png)

**Comment by ashraf789** [comment]
Please try this live app
https://play.google.com/store/apps/details?id=com.ashraf789.cakevpn

It's target sdk is 29
