### ISSUE TITLE
I am always stuck waiting for the server to respond, including your store application, and there is no log information. Do you have any suggestions?

### ISSUE THREAD

**Issue by LiJinJinJIn** [ashraf789/Cake-VPN#96]
I am always stuck waiting for the server to respond, including your store application, and there is no log information. Do you have any suggestions?

**Comment by ashraf789** [comment]
I am also a Samsung user and all the servers(free servers) on the live app working fine. 
As far as I know, China has a strict VPN policy they block all VPN connections. 
Are you trying with a free OVPN file? 
If so then try to set up your own VPN server then try again.
